networks:
  webrtc:
    driver: bridge

services:
  coturn:
    image: coturn/coturn:latest
    container_name: coturn-stun-turn
    ports:
      - "3478:3478/udp"
      - "3478:3478/tcp"
    networks:
      - webrtc
    command:
      - "-n"
      - "--log-file=stdout"
      - "--listening-port=3478"
      - "--fingerprint"
      - "--lt-cred-mech"
      - "--user=webrtc:webrtc123"
      - "--realm=localhost"
    restart: unless-stopped

  janus:
    image: canyan/janus-gateway:latest
    container_name: janus-webrtc-gateway
    ports:
      - "8088:8088"
      - "20000-20100:20000-20100/udp"
    networks:
      - webrtc
    volumes:
      - ./janus-config:/usr/local/etc/janus:rw
    depends_on:
      - coturn
    restart: unless-stopped
