services:
  coturn:
    image: coturn/coturn:latest
    container_name: coturn-stun-turn
    network_mode: host
    command:
      - "-n"
      - "--log-file=stdout"
      - "--listening-port=3478"
      - "--fingerprint"
      - "--lt-cred-mech"
      - "--user=webrtc:webrtc123"
      - "--realm=localhost"
    restart: unless-stopped

  janus:
    image: canyan/janus-gateway:latest
    container_name: janus-webrtc-gateway
    network_mode: host
    volumes:
      - ./janus-config:/usr/local/etc/janus:rw
    restart: unless-stopped
