services:
  janus:
    image: canyan/janus-gateway:latest
    container_name: janus-webrtc-gateway
    ports:
      - "8088:8088"
      - "20000-20100:20000-20100/udp"
    volumes:
      - ./janus-config:/usr/local/etc/janus:rw
    restart: unless-stopped
